---
- name: Add signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx
    - deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx

- name: Install nginx
  apt: update_cache=yes name=nginx

- name: Make directory for SSL files
  file:
    state: directory
    path: /etc/nginx/ssl

- name: Upload certificate
  copy: src={{ ssl_certificate }} dest=/etc/nginx/ssl/ghost.crt

- name: Upload certificate key
  copy: src={{ ssl_certificate_key }} dest=/etc/nginx/ssl/ghost.key

- name: Upload dhparam.pem
  copy: src={{ ssl_dhparam }} dest=/etc/nginx/ssl/dhparam.pem

- name: Upload trusted certificate
  copy:
    src: "{{ ssl_trusted_certificate }}"
    dest: /etc/nginx/ssl/trusted_certificate.pem

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
